name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # 不装这个会报错
      - name: Test with pytest
        run: |
          pytest

#| 行                                     | 含义                                                            |                    |
#| ------------------------------------- | ------------------------------------------------------------- | ------------------ |
#| `name: Python package`                | 这是 GitHub Actions 工作流的名称，在 Actions 页面显示。                      |                    |
#| `on: [push]`                          | 表示每当你 push 代码时，就会触发这个工作流。                                     |                    |
#| `jobs:`                               | 一个 workflow 可以包含多个 job（任务）。这里只有一个：`build`。                    |                    |
#| `build:`                              | 定义一个名为 "build" 的任务。                                           |                    |
#| `runs-on: ubuntu-latest`              | 告诉 GitHub 使用 Linux (Ubuntu) 服务器运行这个任务。                        |                    |
#| `strategy.matrix.python-version`      | 告诉它要在多个 Python 版本上测试（这里是 3.10 和 3.13）。GitHub 会自动并行运行这两个版本的测试。 |                    |
#| `steps:`                              | 任务的执行步骤。                                                      |                    |
#| `- uses: actions/checkout@v4`         | 检出（clone）你的仓库代码到 runner（虚拟机）。                                 |                    |
#| `- name: Set up Python ...`           | 安装并设置所需 Python 版本。                                            |                    |
#| `uses: actions/setup-python@v5`       | GitHub 官方动作，用来安装 Python 环境。                                   |                    |
#| `with: python-version:`               | 告诉它具体版本（来自上面的 matrix）。                                        |                    |
#| `- name: Install dependencies`        | 安装依赖项（比如 pytest）。                                             |                    |
#| `run:                                 | `                                                             | 表示接下来的多行命令将在终端里执行。 |
#| `python -m pip install --upgrade pip` | 更新 pip。                                                       |                    |
#| `pip install pytest`                  | 安装 pytest，这样下面就能运行测试了。                                        |                    |
#| `- name: Test with pytest`            | 命名测试步骤。                                                       |                    |
#| `pytest`                              | 执行 pytest，自动发现 `test_*.py` 文件并运行。                             |                    |
